/* Al Azim Consulting — shared translations (EN default) */
window.I18N = {
en:{gal_e:"Moments",gal_t:"From Our Journey",gal_d:"University visits, festivals and our students — live from the Al Azim family.",c_eyebrow2:"Meet Us",g_eyebrow2:"Our Community",sb1_t:"More Than 38 Universities, One Right Choice",sb1_d:"Every student's goal is different. We listen to yours, compare programs and fees honestly, and place you where you will truly succeed.",sb1_b:"Explore Universities",sb2_t:"A Real Office, Real People in Istanbul",sb2_d:"We are not just a website. Visit our office in Bahçelievler — have a tea, meet your advisor face to face and get answers in your own language.",sb2_b:"Contact Us",sb3_t:"From First Application to Graduation Day",sb3_d:"Our support does not end at enrollment. Residence permit, denklik, dormitory, part-time work — the Al Azim family stays with you until you hold your diploma.",sb4_t:"Join a Community, Not Just a University",sb4_d:"Festivals, national holidays, student meetups — with Al Azim you join hundreds of Turkmen students who already call Istanbul home.",sb4_b:"See Our News",wt_t:"Study in the Heart of Two Continents",wt_d:"World-class universities, affordable living and a culture close to home — discover why thousands of Turkmen students choose Turkey every year.",wt_btn:"Discover Why Turkey",nav_guide:"Student Guide",p_btn:"Price List",p_from:"Tuition from",p_year:"/year",p_note:"Special for students from Turkmenistan: the deposit is half of the annual tuition fee.",p_ask:"Ask on WhatsApp",p_prices:"2026–2027 Tuition Fees",p_prep:"Prep. Programs",nav_team:"Our Team",nav_prog:"Programs",nav_why:"Why Turkey",nav_faq:"FAQ",nav_home:"Home",nav_about:"About",nav_services:"Services",nav_uni:"Universities",nav_denklik:"Equivalency",nav_news:"News",nav_contact:"Contact",
 apply:"Apply Now",learn:"Learn More",send_wa:"Send via WhatsApp",
 f_about:"Al Azim Consulting supports international students with university admission, residence and work permits, and legal guidance in Turkey. Official representative of universities in Turkey.",
 f_links:"Quick Links",f_contact:"Contact & Office",f_addr:"Şirinevler Mah. Meriç Sk. No:20, 34188 Bahçelievler / İstanbul",
 f_rights:"All rights reserved.",
 cta_title:"Begin your journey to Turkey",cta_sub:"Contact us today and let's start your acceptance process at universities in Turkey — free application, no exams.",cta_call:"Talk to an Advisor",
 st_students:"Students Placed",st_uni:"Partner Universities",st_rate:"First-Choice Approval",st_countries:"Countries Served",
 uni_lab:"Partner Universities in Turkey"
},
tr:{gal_e:"Kareler",gal_t:"Yolculuğumuzdan Kareler",gal_d:"Üniversite ziyaretleri, festivaller ve öğrencilerimiz — Al Azim ailesinden canlı kareler.",c_eyebrow2:"Bizimle Tanış",g_eyebrow2:"Topluluğumuz",sb1_t:"38+ Üniversite, Tek Doğru Tercih",sb1_d:"Her öğrencinin hedefi farklı. Seni dinliyor, bölümleri ve ücretleri dürüstçe karşılaştırıyor, gerçekten başarılı olacağın yere yerleştiriyoruz.",sb1_b:"Üniversiteleri Keşfet",sb2_t:"İstanbul'da Gerçek Bir Ofis, Gerçek İnsanlar",sb2_d:"Sadece bir web sitesi değiliz. Bahçelievler'deki ofisimize gel, çayını iç, danışmanınla yüz yüze tanış, sorularının cevabını kendi dilinde al.",sb2_b:"Bize Ulaş",sb3_t:"İlk Başvurudan Mezuniyet Gününe",sb3_d:"Desteğimiz kayıtla bitmiyor. Oturum izni, denklik, yurt, part-time iş — Al Azim ailesi diploman elinde olana kadar yanında.",sb4_t:"Sadece Üniversiteye Değil, Bir Aileye Katıl",sb4_d:"Festivaller, milli bayramlar, öğrenci buluşmaları — Al Azim'le, İstanbul'u çoktan evi yapmış yüzlerce Türkmen öğrencinin arasına katılıyorsun.",sb4_b:"Gündemi Gör",wt_t:"İki Kıtanın Kalbinde Eğitim",wt_d:"Dünya standartlarında üniversiteler, uygun yaşam maliyeti ve kendi kültürüne yakın bir ortam — binlerce Türkmen öğrencinin her yıl neden Türkiye'yi seçtiğini keşfet.",wt_btn:"Neden Türkiye'yi Keşfet",nav_guide:"Öğrenci Rehberi",p_btn:"Fiyat Listesi",p_from:"Yıllık ücret",p_year:"/yıl",p_note:"Türkmenistanlı öğrencilere özel: depozito, yıllık ücretin yarısıdır.",p_ask:"WhatsApp'tan Sor",p_prices:"2026–2027 Eğitim Ücretleri",p_prep:"Hazırlık Programları",nav_team:"Ekibimiz",nav_prog:"Programlar",nav_why:"Neden Türkiye",nav_faq:"SSS",nav_home:"Ana Sayfa",nav_about:"Hakkımızda",nav_services:"Hizmetler",nav_uni:"Üniversiteler",nav_denklik:"Denklik",nav_news:"Gündem",nav_contact:"İletişim",
 apply:"Hemen Başvur",learn:"Daha Fazla",send_wa:"WhatsApp ile Gönder",
 f_about:"Al Azim Consulting; üniversite kabulü, oturum ve çalışma izinleri ile Türkiye'deki hukuki süreçlerde uluslararası öğrencilere destek verir. Türkiye'deki üniversitelerin resmi temsilcisi.",
 f_links:"Hızlı Bağlantılar",f_contact:"İletişim & Ofis",f_addr:"Şirinevler Mah. Meriç Sk. No:20, 34188 Bahçelievler / İstanbul",
 f_rights:"Tüm hakları saklıdır.",
 cta_title:"Türkiye yolculuğuna başla",cta_sub:"Bugün bizimle iletişime geçin, Türkiye'deki üniversitelere kabul sürecinizi başlatalım — sınavsız, ücretsiz başvuru.",cta_call:"Danışmanla Görüş",
 st_students:"Yerleştirilen Öğrenci",st_uni:"Partner Üniversite",st_rate:"İlk Tercihte Kabul",st_countries:"Hizmet Verilen Ülke",
 uni_lab:"Türkiye'deki Partner Üniversiteler"
},
tk:{gal_e:"Pursatlar",gal_t:"Ýolumyzdan pursatlar",gal_d:"Uniwersitet saparlary, festiwallar we talyplarymyz — Al Azim maşgalasyndan janly pursatlar.",c_eyebrow2:"Biziň bilen tanşyň",g_eyebrow2:"Jemgyýetimiz",sb1_t:"38+ uniwersitet, ýeke dogry saýlaw",sb1_d:"Her talybyň maksady başga. Sizi diňleýäris, bölümleri we tölegleri dogruçyl deňeşdirýäris, hakykatdanam üstünlik gazanjak ýeriňize ýerleşdirýäris.",sb1_b:"Uniwersitetleri öwreniň",sb2_t:"Stambulda hakyky ofis, hakyky adamlar",sb2_d:"Biz diňe web sahypasy däl. Bahçelievlerdäki ofisimize geliň, çaý içiň, maslahatçyňyz bilen ýüzbe-ýüz tanşyň, soraglaryňyza öz diliňizde jogap alyň.",sb2_b:"Habarlaşyň",sb3_t:"Ilkinji ýüz tutmadan uçurym gününe çenli",sb3_d:"Goldawymyz hasaba alynmak bilen gutarmaýar. Ýaşaýyş rugsady, denklik, umumy ýaşaýyş jaýy, iş — Al Azim maşgalasy diplomyňyz eliňize gelýänçä ýanyňyzda.",sb4_t:"Diňe uniwersitete däl, maşgala goşulyň",sb4_d:"Festiwallar, milli baýramçylyklar, talyp duşuşyklary — Al Azim bilen Stambuly eýýäm öýi eden ýüzlerçe türkmen talybynyň arasyna goşulýarsyňyz.",sb4_b:"Habarlary görüň",wt_t:"Iki yklymyň ýüreginde bilim",wt_d:"Dünýä derejesindäki uniwersitetler, elýeterli ýaşaýyş we öz medeniýetiňe ýakyn gurşaw — müňlerçe türkmen talybynyň her ýyl näme üçin Türkiýäni saýlaýandygyny öwreniň.",wt_btn:"Näme üçin Türkiýe",nav_guide:"Talyp gollanmasy",p_btn:"Bahalaryň sanawy",p_from:"Ýyllyk töleg",p_year:"/ýyl",p_note:"Türkmenistanly talyplara ýörite: depozit ýyllyk tölegiň ýarysydyr.",p_ask:"WhatsApp-dan sora",p_prices:"2026–2027 okuw tölegleri",p_prep:"Taýýarlyk okuwlary",nav_team:"Toparymyz",nav_prog:"Maksatnamalar",nav_why:"Näme üçin Türkiýe",nav_faq:"Soraglar",nav_home:"Baş sahypa",nav_about:"Biz barada",nav_services:"Hyzmatlar",nav_uni:"Uniwersitetler",nav_denklik:"Deňlik",nav_news:"Habarlar",nav_contact:"Habarlaşmak",
 apply:"Ýüz tutmak",learn:"Giňişleýin",send_wa:"WhatsApp arkaly iber",
 f_about:"Al Azim Consulting uniwersitete kabul, ýaşaýyş we iş rugsatlary hem-de Türkiýedäki hukuk meselelerinde halkara talyplara goldaw berýär. Türkiýedäki uniwersitetleriň resmi wekili.",
 f_links:"Çalt baglanyşyklar",f_contact:"Habarlaşmak & Ofis",f_addr:"Şirinevler Mah. Meriç Sk. No:20, 34188 Bahçelievler / Stambul",
 f_rights:"Ähli hukuklar goralan.",
 cta_title:"Türkiýä syýahatyňyza başlaň",cta_sub:"Şu gün biz bilen habarlaşyň — synagsyz, mugt ýüz tutma bilen Türkiýedäki uniwersitetlere kabul prosesiňizi başladalyň.",cta_call:"Maslahatçy bilen gepleş",
 st_students:"Ýerleşdirilen talyp",st_uni:"Hyzmatdaş uniwersitet",st_rate:"Ilkinji saýlawda kabul",st_countries:"Hyzmat edilýän ýurt",
 uni_lab:"Türkiýedäki hyzmatdaş uniwersitetler"
},
ru:{gal_e:"Моменты",gal_t:"Кадры нашего пути",gal_d:"Визиты в университеты, фестивали и наши студенты — живые кадры семьи Al Azim.",c_eyebrow2:"Познакомьтесь с нами",g_eyebrow2:"Наше сообщество",sb1_t:"38+ университетов — один верный выбор",sb1_d:"Цель каждого студента своя. Мы слушаем вас, честно сравниваем программы и цены и помогаем поступить туда, где вы действительно преуспеете.",sb1_b:"Смотреть университеты",sb2_t:"Настоящий офис и живые люди в Стамбуле",sb2_d:"Мы не просто сайт. Приходите в наш офис в Бахчелиэвлер: чашка чая, личная встреча с консультантом и ответы на вашем языке.",sb2_b:"Связаться с нами",sb3_t:"От первой заявки до дня выпуска",sb3_d:"Наша поддержка не заканчивается зачислением. ВНЖ, denklik, общежитие, подработка — семья Al Azim рядом, пока диплом не окажется у вас в руках.",sb4_t:"Вступайте не просто в вуз, а в семью",sb4_d:"Фестивали, национальные праздники, студенческие встречи — с Al Azim вы присоединяетесь к сотням туркменских студентов, для которых Стамбул уже стал домом.",sb4_b:"Наши новости",wt_t:"Учёба в сердце двух континентов",wt_d:"Университеты мирового уровня, доступная жизнь и близкая культура — узнайте, почему тысячи туркменских студентов каждый год выбирают Турцию.",wt_btn:"Почему Турция",nav_guide:"Студенту",p_btn:"Цены на обучение",p_from:"Стоимость от",p_year:"/год",p_note:"Специально для студентов из Туркменистана: депозит составляет половину годовой оплаты.",p_ask:"Спросить в WhatsApp",p_prices:"Стоимость обучения 2026–2027",p_prep:"Подготовительные программы",nav_team:"Наша команда",nav_prog:"Программы",nav_why:"Почему Турция",nav_faq:"Вопросы",nav_home:"Главная",nav_about:"О нас",nav_services:"Услуги",nav_uni:"Университеты",nav_denklik:"Признание диплома",nav_news:"Новости",nav_contact:"Контакты",
 apply:"Подать заявку",learn:"Подробнее",send_wa:"Отправить в WhatsApp",
 f_about:"Al Azim Consulting помогает иностранным студентам с поступлением в университеты, видом на жительство, разрешением на работу и юридическим сопровождением в Турции. Официальный представитель университетов Турции.",
 f_links:"Быстрые ссылки",f_contact:"Контакты и офис",f_addr:"Şirinevler Mah. Meriç Sk. No:20, 34188 Бахчелиэвлер / Стамбул",
 f_rights:"Все права защищены.",
 cta_title:"Начните свой путь в Турцию",cta_sub:"Свяжитесь с нами сегодня — бесплатная заявка без экзаменов, и мы начнём ваш процесс поступления в университеты Турции.",cta_call:"Поговорить с консультантом",
 st_students:"Зачислено студентов",st_uni:"Университетов-партнёров",st_rate:"Одобрение по 1-му выбору",st_countries:"Стран обслуживания",
 uni_lab:"Университеты-партнёры в Турции"
}
};

window.applyLang = function(l){
  const dict = Object.assign({}, I18N[l]||I18N.en, (window.PAGE_I18N&&window.PAGE_I18N[l])||{});
  document.documentElement.lang = l;
  document.querySelectorAll('[data-i18n]').forEach(el=>{
    const k=el.getAttribute('data-i18n');
    if(dict[k]!==undefined) el.innerHTML=dict[k];
  });
  document.querySelectorAll('[data-i18n-ph]').forEach(el=>{
    const k=el.getAttribute('data-i18n-ph');
    if(dict[k]!==undefined) el.placeholder=dict[k];
  });
  document.querySelectorAll('button[data-l]').forEach(b=>b.classList.toggle('on',b.dataset.l===l));
  document.querySelectorAll('.langcur .lc').forEach(el=>el.textContent=l.toUpperCase());
  try{localStorage.setItem('alazim_lang',l)}catch(e){}
};
